POST http://localhost:3000 HTTP/1.1
Content-type: application/json

{
    "id": 12,
    "name": "Asaad",
    "course": "MWA",
    "grade": "95"
}

###

GET http://localhost:3000/grades HTTP/1.1
Content-type: application/json

### 
PUT http://localhost:3000 HTTP/1.1
Content-type: application/json
{
    "id": 1,
    "name": "Asaad",
    "course": "MWA",
    "grade": "90"
}
